export const CONNECT_REQUEST = 'SERVICES/SESSION/CONNECT_REQUEST';
export const CONNECT_SUCCESS = 'SERVICES/SESSION/CONNECT_SUCCESS';
export const CONNECT_FAILURE = 'SERVICES/SESSION/CONNECT_FAILURE';

export const IS_OWNER_REQUEST = 'SERVICES/SESSION/IS_OWNER_REQUEST';
export const IS_OWNER_SUCCESS = 'SERVICES/SESSION/IS_OWNER_SUCCESS';
export const IS_OWNER_FAILURE = 'SERVICES/SESSION/IS_OWNER_FAILURE';

export const SET_CURRENT_BLOCK_NUMBER = 'SERVICES/SESSION/SET_CURRENT_BLOCK_NUMBER';
