export const CONNECT_REQUEST = 'SERVICES/SESSION/CONNECT_REQUEST';
export const CONNECT_SUCCESS = 'SERVICES/SESSION/CONNECT_SUCCESS';
export const CONNECT_FAILURE = 'SERVICES/SESSION/CONNECT_FAILURE';

