export const CREATE_VALIDATOR_REQUEST = 'ENTITIES/VALIDATORS/CREATE_VALIDATOR_REQUEST';
export const CREATE_VALIDATOR_SUCCESS = 'ENTITIES/VALIDATORS/CREATE_VALIDATOR_SUCCESS';
export const CREATE_VALIDATOR_FAILURE = 'ENTITIES/VALIDATORS/CREATE_VALIDATOR_FAILURE';

export const DEPOSIT_VALIDATOR_REQUEST = 'ENTITIES/VALIDATORS/DEPOSIT_VALIDATOR_REQUEST';
export const DEPOSIT_VALIDATOR_SUCCESS = 'ENTITIES/VALIDATORS/DEPOSIT_VALIDATOR_SUCCESS';
export const DEPOSIT_VALIDATOR_FAILURE = 'ENTITIES/VALIDATORS/DEPOSIT_VALIDATOR_FAILURE';

export const FETCH_VALIDATOR_REQUEST = 'ENTITIES/VALIDATORS/FETCH_VALIDATOR_REQUEST';
export const FETCH_VALIDATOR_SUCCESS = 'ENTITIES/VALIDATORS/FETCH_VALIDATOR_SUCCESS';
export const FETCH_VALIDATOR_FAILURE = 'ENTITIES/VALIDATORS/FETCH_VALIDATOR_FAILURE';

export const FETCH_VALIDATORS_REQUEST = 'ENTITIES/VALIDATORS/FETCH_VALIDATORS_REQUEST';
export const FETCH_VALIDATORS_SUCCESS = 'ENTITIES/VALIDATORS/FETCH_VALIDATORS_SUCCESS';
export const FETCH_VALIDATORS_FAILURE = 'ENTITIES/VALIDATORS/FETCH_VALIDATORS_FAILURE';

export const PAUSE_VALIDATOR_REQUEST = 'ENTITIES/VALIDATORS/PAUSE_VALIDATOR_REQUEST';
export const PAUSE_VALIDATOR_SUCCESS = 'ENTITIES/VALIDATORS/PAUSE_VALIDATOR_SUCCESS';
export const PAUSE_VALIDATOR_FAILURE = 'ENTITIES/VALIDATORS/PAUSE_VALIDATOR_FAILURE';

export const START_VALIDATOR_REQUEST = 'ENTITIES/VALIDATORS/START_VALIDATOR_REQUEST';
export const START_VALIDATOR_SUCCESS = 'ENTITIES/VALIDATORS/START_VALIDATOR_SUCCESS';
export const START_VALIDATOR_FAILURE = 'ENTITIES/VALIDATORS/START_VALIDATOR_FAILURE';

export const UPDATE_VALIDATOR = 'ENTITIES/VALIDATORS/UPDATE_VALIDATOR';

export const WITHDRAW_VALIDATOR_REQUEST = 'ENTITIES/VALIDATORS/WITHDRAW_VALIDATOR_REQUEST';
export const WITHDRAW_VALIDATOR_SUCCESS = 'ENTITIES/VALIDATORS/WITHDRAW_VALIDATOR_SUCCESS';
export const WITHDRAW_VALIDATOR_FAILURE = 'ENTITIES/VALIDATORS/WITHDRAW_VALIDATOR_FAILURE';
